{% set name = "plus_slurm" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/plus_slurm-{{ version }}.tar.gz
  sha256: f68ae230483e81b0f1f69c71fa6379bda0ad436cda2a8f095860ce667e729a37

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-regex-commit
    - pip
  run:
    - python >={{ python_min }}
    - jinja2
    - future
    - humanfriendly
    - six
    - numpy
    - psutil

test:
  imports:
    - plus_slurm
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Convenient Python Abstraction for the Slurm based cluster at the PLUS
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://gitlab.com/thht/plus-slurm/
  doc_url: https://plus-slurm.readthedocs.io/

extra:
  recipe-maintainers:
    - thht
